import { Commitment } from "@solana/web3.js";

export const CONFIRMED = "confirmed" as Commitment;
export const FINALIZED = "finalized" as Commitment;

export const DEX_PROGRAMS = {
  RAYDIUM_AMM: "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8",
  RAYDIUM_CLMM: "CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK",
  RAYDIUM_CPMM: "CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C",
  RAYDIUM_LAUNCHLAB: "LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj",
  METEORA_AMM: "Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB",
  METEORA_DLMM: "LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo",
  METEORA_DAMM_V2: "cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG",
  DEXLAB_SWAP: "DSwpgjMvXhtGn6BsbqmacdBZyfLj6jSWf3HJpdJtmg6N",
  PENGUIN_FINANCE: "PSwapMdSai8tjrEXcxFeQth87xC4rRsa4VA5mhGhXkP",
  MOONIT: "MoonCVVNZFSYkqNXP6bxHLPL6QQJiMagDL3qcqUQTrG",
  SOLAYER: "endoLNCKTqDn8gSVnN2hDdpgACUPWHZTwoYnnMybpAT",
  SABER_DECIMALS: "DecZY86MU5Gj7kppfUCEmd4LbXXuyZH1yHaP2NTqdiZB",
  PHOENIX: "PhoeNiXZ8ByJGLkxNfZRnkUfjvmuYqLR89jjFHGqdXY",
  BOOP_FUN: "boop8hVGQGqehUK2iVEMEnMrL5RbjywRzHKBmBE7ry4",
  STABBLE_STABLE_SWAP: "swapNyd8XiQwJ6ianp9snpu4brUqFxadzvHebnAXjJZ",
  DYNAMIC_BONDING_CURVE: "dbcij3LWUppWqq96dh6gJWwBifmcGfLSB5D4DuSMaqN",
  "1DEX": "DEXYosS6oEGvk8uCDayvwEZz4qEyDJRf9nFgYCaqPMTm",
  CREMA: "CLMM9tUoggJu2wagPkkqs9eFG4BWhVBZWkP1qv3Sp7tR",
  BONKSWAP: "BSwp6bEBihVLdqJRKGgzjcGLHkcTuzmSo1TQkHepzH8p",
  WOOFI: "WooFif76YGRNjk1pA8wCsN67aQsD9f9iLsz4NcJ1AVb",
  ZEROFI: "ZERor4xhbUycZ6gb9ntrhqscUcZmAbQDjEAtCf4hbZY",
  PUMP_FUN_AMM: "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA",
  VIRTUALS: "5U3EU2ubXtK84QcRjWVmYt9RaDyA8gKxdUrPFXmZyaki",
  SOLFI: "SoLFiHG9TfgtdUXUjWAxi3LtvYuFyDLVhBWxdMZxyCe",
  STEPN: "Dooar9JkhdZ7J3LHN3A7YCuoGRUggXhQaG4kijfLGU2j",
  GOONFI: "goonERTdGsjnkZqWuVjs73BZ3Pb9qoCUdBUL17BnS5j",
  FLUXBEAM: "FLUXubRmkEi2q6K3Y9kBPg9248ggaZVsoSFhtJHSrm1X",
  INVARIANT: "HyaB3W9q6XdA5xwpU4XnSZV94htfmbmqJXZcEbRaJutt",
  PUMP_FUN: "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P",
  PERENA: "NUMERUNsFCP3kuNmWZuXtm1AaQCPj9uw6Guv2Ekoi5P",
  SANCTUM_INFINITY: "5ocnV1qiCgaQR8Jb8xWnVbApfaygJ8tNoZfgPwsgx9kx",
  SABER: "SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ",
  PANCAKESWAP: "HpNfyc2Saw7RKkQd8nEL4khUcuPhQ7WwY1B2qjx8jxFq",
  SANCTUM: "stkitrT1Uoy18Dk1fTrgPw8W6MVzoCfYoAFT4MLsmhq",
  TESSERAV: "TessVdML9pBGgG9yGks7o4HewRaXVAMuoVj4x83GLQH",
  TOKEN_SWAP: "SwaPpA9LAaLfeLi3a68M4DjnLqgtticKg6CnyNwgAC8",
  STABBLE_WEIGHTED_SWAP: "swapFpHZwjELNnjvThjajtiVmkz3yPQEHjLtka2fwHW",
  ORCA_V1: "DjVE6JNiYqPL2QXyCUUh8rNjHrbz9hXHNYt99MQ59qw1",
  HUMIDIFI: "9H6tua7jkLhdm3w8BvgpTn5LZNU7g4ZynDmCiNN3q6Rp",
  WHIRLPOOL: "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc",
  OBRIC_V2: "obriQD1zbpyLz95G5n7nJe6a4DPjpFwa5XYPoNm113y",
  MERCURIAL: "MERLuDFBMmsHnsBPZw2sDQZHvXFMwp8EdjudcU2HKky",
  PERPS: "PERPHjGBqRHArX4DySjwM6UJHiR3sWAatqfdBS2qQJu",
  HELIUM_NETWORK: "treaf4wWBBty3fHdyBpo35Mz84M8k3heKXmjmi9vFt5",
  OPENBOOK_V2: "opnb2LAfJYbRMAHHvqjCwQxanZn7ReEHp1k81EohpZb",
  LIFINITY_V2: "2wT8Yq49kHgDzXuPxZSaeLaH1qbmGXtEyPy64bL7aD3c",
  GAVEL: "srAMMzfVHVAtgSJc8iH6CfKzuWuUTzLHVCE81QU1rgi",
  SAROS: "SSwapUtytfBdBn1b9NUGG6foMVPtcWgpRU32HToDUZr",
  GOOSEFX_GAMMA: "GAMMA7meSFWaBXF25oSUgmGRwaW6sCMFLmBNiMSdbHVT",
  BYREAL: "REALQqNEomY6cQGZJUGwywTBD2UmDT32rZcNnfxQ5N2",
  CROPPER: "H8W3ctz92svYg6mkn1UtGfu2aQr2fnUFHM1RhScEtQDt",
  ALDRIN: "AMM55ShdkoGRB5jVYPjWziwk8m5MpwyDgsMWHaMSQWH6",
  ALDRIN_V2: "CURVGoZn8zycx6FXwwevgBTB2gVvdbGTEpvMJDbgs2t4",
  GUACSWAP: "Gswppe6ERWKpUTXvRPfXdzHhiCyJvLadVvXGfdpBqcE1",
  ORCA_V2: "9W959DqEETiGZocYWCQPaJ6sBmUzgfxXfqGeTEdp3aQP",
};

export const SLIPPAGE_TOLERANCE: number = 0;

export const JITO_TIP_AMOUNT: number = 0.0001;

export const JITO_TIP_ACCOUNTS: string[] = [
  "Cw8CFyM9FkoMi7K7Crf6HNQqf4uEMzpKw6QNghXLvLkY",
  "DttWaMuVvTiduZRnguLF7jNxTgiMBZ1hyAumKUiL2KRL",
  "96gYZGLnJYVFmbjzopPSU6QiEV5fGqZNyN9nmNhvrZU5",
  "3AVi9Tg9Uo68tJfuvoKvqKNWKkC5wPdSSdeBnizKZ6jT",
  "HFqU5x63VTqvQss8hp11i4wVV8bD44PvwucfZ2bU7gRe",
  "ADaUMid9yfUytqMBgopwjb2DTLSokTSzL1zt6iGPaS49",
  "ADuUkR4vqLUMWXxW9gh6D6L8pMSawimctcNZ5pGwDcEt",
  "DfXygSm4jCyNCybVYYK6DwvWqjKee8pbDmJGcLWNDXjh",
];

export const JITO_ENDPOINT = "https://ny.mainnet.block-engine.jito.wtf/api/v1/bundles"

export const HELIUS_TIP_AMOUNT = 0.001;

export const HELIUS_TIP_ACCOUNTS: string[] = [
  "4ACfpUFoaSD9bfPdeu6DBt89gB6ENTeHBXCAi87NhDEE",
  "D2L6yPZ2FmmmTKPgzaMKdhu6EWZcTpLy1Vhx8uvZe7NZ",
  "9bnz4RShgq1hAnLnZbP8kbgBg1kEmcJBYQq3gQbmnSta",
  "5VY91ws6B2hMmBFRsXkoAAdsPHBJwRfBht4DXox3xkwn",
  "2nyhqdwKcJZR2vcqCyrYsaPVdAnFoJjiksCXJ7hfEYgD",
  "2q5pghRs6arqVjRvT5gfgWfWcHWmw1ZuCzphgd5KfWGJ",
  "wyvPkWjVZz1M8fHQnMMCDTQDbkManefNNhweYk5WkcF",
  "3KCKozbAaF75qEU33jtzozcJ29yJuaLJTy2jFdzUY8bT",
  "4vieeGHPYPG2MmyPRcYjdiDmmhN3ww7hsFNap8pVN3Ey",
  "4TQLFNWK8AovT1gFvda5jfw2oJeRMKEmw7aH6MGBJ3or",
];

export const HELIUS_ENDPOINT = "http://ewr-sender.helius-rpc.com/fast"
